#!/bin/bash

#jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid

jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension